// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr8EFgYH4lr6Y8J5pWigphIjixD4Pcb5Q',
    appId: '1:308669370345:web:61587d1864d57784764578',
    messagingSenderId: '308669370345',
    projectId: 'trackify-c31',
    authDomain: 'trackify-c31.firebaseapp.com',
    storageBucket: 'trackify-c31.firebasestorage.app',
    measurementId: 'G-Y9BC9386EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIyxpF7LCJZSE1VnIA4ZVz4Q4onkE2pqw',
    appId: '1:308669370345:android:009d647716fdac70764578',
    messagingSenderId: '308669370345',
    projectId: 'trackify-c31',
    storageBucket: 'trackify-c31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32Zy-C_6i7oFSFIRH--ysoUtWZEsWupA',
    appId: '1:308669370345:ios:17804c8357f48b62764578',
    messagingSenderId: '308669370345',
    projectId: 'trackify-c31',
    storageBucket: 'trackify-c31.firebasestorage.app',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32Zy-C_6i7oFSFIRH--ysoUtWZEsWupA',
    appId: '1:308669370345:ios:17804c8357f48b62764578',
    messagingSenderId: '308669370345',
    projectId: 'trackify-c31',
    storageBucket: 'trackify-c31.firebasestorage.app',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr8EFgYH4lr6Y8J5pWigphIjixD4Pcb5Q',
    appId: '1:308669370345:web:bab07c292e404da9764578',
    messagingSenderId: '308669370345',
    projectId: 'trackify-c31',
    authDomain: 'trackify-c31.firebaseapp.com',
    storageBucket: 'trackify-c31.firebasestorage.app',
    measurementId: 'G-NTWF6MZ0WV',
  );
}
